### ISSUE TITLE
Creating a user requires us to hash the password ourselves

### ISSUE THREAD

**Issue by pieterdp** [GruppoMeta/Movio#1]
When creating or modifying a user, we have to hash (by guessing we arrived at md5) the new or modified password ourselves. The software does not do this for us, but expects a md5-hashed password, as this is what gets stored.

The password is also stored extremely insecure, with only a weak hashing algorithm (md5) and no salt.

Expectation: passwords are entered (never displayed) as plain text, and securely hashed and salted by the software.

**Comment by danieleugoletti** [comment]
Fix in v 2.0.0
