### ISSUE TITLE
Changing passwords

### ISSUE THREAD

**Issue by AJGI** [GruppoMeta/Movio#10]
Dear colleages and developers,

We installed many MOVIO each one with its code, database, users, etc.

We have a problem when we change the default password for the admin user. And we cannot enter anymore through this user to this instance.  We can sign in in other instance of MOVIO and change to this new one.

Any of you have the same problem? Any idea?

Thanks in advance.

**Comment by danieleugoletti** [comment]
This issue was fixed in v2.0.3

Please let me know if you using a previous version.

**Comment by AJGI** [comment]
Thanks for the answer.
We are running 1.8 version. I guess, we should update the MOVIO version.
Is there some instructions to migrate the 1.8 to the 2.0.3? Or we should develope manually the websites again?
