### ISSUE TITLE
GLIZY framework E_ERROR : Call to a member function getIconFileName() on a non-object

### ISSUE THREAD

**Issue by AJGI** [GruppoMeta/Movio#11]
The Media Archive don't show the images that we uploaded (you can see attached screen shot).

And when we ask for the Preview option it appers this error message:

GLIZY framework E_ERROR : Call to a member function getIconFileName() on a non-object

Any idea?

Thanks in advance!
![movio-mediaarchive](https://user-images.githubusercontent.com/18439777/34987443-740184e8-fabb-11e7-99cc-035ada1c7c8c.PNG)

**Comment by danieleugoletti** [comment]
what version of MOVIO you are using?
check the file application/config/config_common.xml

**Comment by AJGI** [comment]
Thanks for the path.
Version 1.8

**Comment by danieleugoletti** [comment]
Please upgrade to latest version
