### ISSUE TITLE
Error in "Template e colori" tab

### ISSUE THREAD

**Issue by urbini** [GruppoMeta/Movio#12]
In Movio version 2.0.1, when I edit a page and go to the "Template e colori" tab, I get a page with a warning message as in the following attached file:
![errore hasattribute 1](https://user-images.githubusercontent.com/23096935/35336865-fc94ea34-0119-11e8-95f4-7a7750780475.jpg)

Actually, this warning is caused by a php fatal error like the following:
PHP Fatal error:  Call to a member function hasAttribute() on a non-object in /home/sbafiren/public_html/movio/movio_test2/core/classes/org/glizy/compilers/PageType.php on line 134
(but the file PageType.php is identical to that one of version 1.8 with which I've used the "Template e colori" tab)

This happen with "Movio" template. If I select Minimal in blue or Sliding windows template, I don't get neither the fatal error nor the warning message, but the "Template e colori" tab is empty. See the following screenshot: 
![errore hasattribute 2](https://user-images.githubusercontent.com/23096935/35337329-264dd8b2-011b-11e8-88c3-ab436be3ae32.jpg)

**Comment by danieleugoletti** [comment]
Fixed in v2.0.5
