### ISSUE TITLE
500 - Internal Software Error on admin page

### ISSUE THREAD

**Issue by gnfrnc** [GruppoMeta/Movio#16]
Not an issue but a suggest.
I encountered this problem during installation and spent a bit of time in debugging for the reason.
I was able ho access http://mysite.it but got error 500 when getting http://mysite.it/admin
I suppose that during installation is important to edit config file before any access to the site, otherwise cache file are created containing default database credential.
Solution: Delete cache files in cache folder.

**Comment by urbini** [comment]
Hi. I encountered problems due to cache more than once. I just point out that there is a cache directory under the admin one that it has to be empty for problems with the admin panel. 
So two cache directories:
/cache
/admin/cache
