### ISSUE TITLE
Back-end / Front-end configuration

### ISSUE THREAD

**Issue by stefd64** [GruppoMeta/Movio#4]
I'd like to configure a public front-end http://www.myserver.com with only SELECT permissions on the database, and a private back-end http://www.myserver.com/admin/ with SELECT, INSERT, UPDATE, DELETE permissions.

Could someone tell me how to do so ?
In particular, there is the file application/config/config.xml for the DB name, username and password, but these are referred to the front-end or to the back-end ?
And, if these are reffered (i.e.) to the front-end, where is the back-end configuration to access the DB ?

**Comment by danieleugoletti** [comment]
Hi
in application/config/config.xml insert the front-end db settings, and in admin/application/config/config.xml insert the back-end db settings.
