### ISSUE TITLE
Onthology builder does not work and problem with templates

### ISSUE THREAD

**Issue by tharr81** [GruppoMeta/Movio#6]
Hello,
my problem with Movio is as follow: when I click on onthology builder ->add new entity nothing is happening:
![onthology](https://user-images.githubusercontent.com/33453807/32493874-c2ed33e6-c3bf-11e7-8103-4f8c707c25f5.jpg)
The second issue is with templates and colors. When I click on it, I receive this error:
![template](https://user-images.githubusercontent.com/33453807/32493977-207c36e2-c3c0-11e7-9fdd-0135e63bb7c5.jpg)
(MOVIO
E_ERROR: Call to a member function hasAttribute() on null)

Thanks in advance for any assistance in solving those issues

**Comment by tharr81** [comment]
There is also a problem with adding new user: 
![movio](https://user-images.githubusercontent.com/33453807/33428093-e63f5bb6-d5c7-11e7-9e89-193075916e62.jpg)

**Comment by urbini** [comment]
Hi.
I had the same problem with users creation, here is how to solve:
in the database table "users_tbl" delete the field user_extid, then delete the content of the directories cache/ and admin/cache.

**Comment by tharr81** [comment]
Hi urbini,
thanks for your advice - it works.

**Comment by danieleugoletti** [comment]
Fixed in version 2.0.2
