### ISSUE TITLE
custom css goes bad

### ISSUE THREAD

**Issue by alyr01** [GruppoMeta/Movio#8]
Hi, we made a page with movio, and I tried to use the "custom css" box under the template making page. (I tried in the Sliding Windows template)
I am not a very experienced in css, I am sure I made a mistake, but result was extraodrinary.
There was an error title not only the webpage, but also instead the editorial page of the template. We had to use an another template. 
Is there anybody who has an idea how can we fix that without reseting the page?

**Comment by urbini** [comment]
I've used the "custom css" box with the Movio template and I had no problems.  Can you give the url of the page?

**Comment by alyr01** [comment]
Of course (www.liget.bparchiv.hu), but now it is in use as a part of an exhibition (with an another template, where I did not use the "custom css" part, only customize with the application form of the template). 
 I attach the picture how it looks like when I try to use that template. It appears on the page and on the customizer surface of the template too.
![movio_hiba](https://user-images.githubusercontent.com/26600275/33127627-8a509ea8-cf89-11e7-93d5-c40c592eb03f.png)

**Comment by urbini** [comment]
I'm sorry I can't help you, I'm not a Movio developer, just a user, and till now I've not yet used the Sliding Windows template, only the Movio template with some customizations.
Regards

**Comment by danieleugoletti** [comment]
I can't reproduce the error, you can send me a screenshot of template > customize page?

**Comment by alyr01** [comment]
I am sorry, but when I try to look at it, instead the customize page the warning message appears which I attached above.

**Comment by danieleugoletti** [comment]
@alyr01 you con verify with version 2.0.2 and clean DB
